#! /bin/sh
set -e

rm -rf config

mkdir -p config/task-lists config/package-lists

add_task ()
{
	local pass="$1"
	shift
	local task

	for task; do
		echo "$task" >> "config/task-lists/livecd-rootfs.chroot_$pass.list"
	done
}

add_package ()
{
	local pass="$1"
	shift
	local pkg

	for pkg; do
		echo "$pkg" >> "config/package-lists/livecd-rootfs.chroot_$pass.list"
	done
}

OPTS=
COMPONENTS=
BINARY_IMAGES=iso-hybrid
MEMTEST=memtest86+
SOURCE='--source false'
BOOTLOADER=syslinux

add_package live lupin-casper ubiquity-frontend-gtk ubiquity-ubuntu-artwork plank-item-ubiquity
add_package install elementary-os-overlay elementary-desktop elementary-standard elementary-minimal
COMPONENTS='main restricted universe multiverse'

lb config noauto \
    --architecture "$ARCH" \
	--mode ubuntu \
	--distribution "$SUITE" \
	--bootstrap-keyring ubuntu-keyring \
    --syslinux-theme elementary-luna \
	--binary-images "$BINARY_IMAGES" \
	--memtest "$MEMTEST" \
	$SOURCE \
	--build-with-chroot false \
	${MIRROR:+--parent-mirror-bootstrap $MIRROR} \
	${COMPONENTS:+--parent-archive-areas "$COMPONENTS"} \
	${KERNEL_FLAVOURS:+--linux-flavours "$KERNEL_FLAVOURS"} \
	--initsystem none \
	--bootloader "$BOOTLOADER" \
	--initramfs-compression gzip \
	$OPTS

ln -s /usr/share/live/build/examples/hooks/all_chroot_pyc-purge.sh config/chroot_local-hooks/
cp auto/hooks/seeds.sh config/chroot_local-hooks/
cp auto/hooks/fix_lightdm.sh config/chroot_local-hooks/
cp auto/hooks/fix_syslinux.sh config/binary_local-hooks/
cp auto/hooks/info.py config/binary_local-hooks/
cp auto/hooks/translations.sh config/binary_local-hooks/
cp auto/hooks/pool.sh config/binary_local-hooks/

mkdir -p config/archives
cp auto/archives/* config/archives/

# set ISO properties
sed -i 's/Ubuntu\ Live/elementary\ OS/' config/binary
sed -i 's/LB_ISO_VOLUME/LB_ISO_VOLUME\=\"elementary OS\"\n#/' config/binary
