#! /bin/sh
set -e

rm -rf config

mkdir -p config/task-lists config/package-lists

add_task ()
{
	local pass="$1"
	shift
	local task

	for task; do
		echo "$task" >> "config/task-lists/livecd-rootfs.chroot_$pass.list"
	done
}

add_package ()
{
	local pass="$1"
	shift
	local pkg

	for pkg; do
		echo "$pkg" >> "config/package-lists/livecd-rootfs.chroot_$pass.list"
	done
}

add_pool ()
{
	local pkg="$1"

	for pkg; do
		echo "$pkg" >> "config/package-lists/livecd-rootfs.binary.list"
	done
}

OPTS=
COMPONENTS=
BINARY_IMAGES=iso
MEMTEST=memtest86+
SOURCE='--source false'
BOOTLOADER=syslinux

add_package live lupin-casper ubiquity-frontend-gtk ubiquity-ubuntu-artwork plank-item-ubiquity
add_package install elementary-os-overlay elementary-desktop elementary-standard elementary-minimal
add_pool pptp-linux sl-modem-daemon ndiswrapper-utils-1.9 ndisgtk libatm1 setserial mouseemu b43-fwcutter bcmwl-kernel-source wvdial grub lupin-support dkms fakeroot patch 
COMPONENTS='main restricted universe multiverse'

lb config noauto \
    --architecture "$ARCH" \
	--mode ubuntu \
	--distribution "$SUITE" \
	--bootstrap-keyring ubuntu-keyring \
    --syslinux-theme elementary-luna \
	--binary-images "$BINARY_IMAGES" \
	--memtest "$MEMTEST" \
	$SOURCE \
	--build-with-chroot false \
	${MIRROR:+--parent-mirror-bootstrap $MIRROR} \
	${COMPONENTS:+--parent-archive-areas "$COMPONENTS"} \
	--package-lists none \
	${KERNEL_FLAVOURS:+--linux-flavours "$KERNEL_FLAVOURS"} \
	--initsystem none \
	--bootloader "$BOOTLOADER" \
	--initramfs-compression gzip \
	$OPTS

ln -s /usr/share/live/build/examples/hooks/all_chroot_pyc-purge.sh config/chroot_local-hooks/
cp auto/hooks/blacklist.sh config/chroot_local-hooks/
cp auto/hooks/fix_lightdm.sh config/chroot_local-hooks/
cp auto/hooks/fix_syslinux.sh config/binary_local-hooks/
cp auto/hooks/set_info.sh config/binary_local-hooks/
cp auto/hooks/pool_clean.sh config/binary_local-hooks/

mkdir -p config/archives
cp auto/archives/* config/archives/
