#! /bin/sh
set -e

. ../../etc/congrego.conf

rm -rf config

mkdir -p config/package-lists

add_task ()
{
	local pass="$1"
	shift
	local task

	for task; do
		echo "!chroot chroot apt-cache dumpavail | grep-dctrl -nsPackage -wFTask $task" >> "config/package-lists/livecd-rootfs.list.chroot_$pass"
	done
}

add_package ()
{
	local pass="$1"
	shift
	local pkg

	for pkg; do
		echo "$pkg" >> "config/package-lists/livecd-rootfs.list.chroot_$pass"
	done
}

CHROOT_HOOKS=
BINARY_HOOKS=
 
add_chroot_hook ()
{
    CHROOT_HOOKS="${CHROOT_HOOKS:+$CHROOT_HOOKS }$1"
}
 
add_binary_hook ()
{
    BINARY_HOOKS="${BINARY_HOOKS:+$BINARY_HOOKS }$1"
}

OPTS=
COMPONENTS=
BINARY_IMAGES=iso-hybrid
MEMTEST=memtest86+
SOURCE='--source false'
BOOTLOADER=syslinux

add_package live lupin-casper ubiquity-frontend-gtk ubiquity-ubuntu-artwork plank-item-ubiquity
add_package install elementary-os-overlay elementary-desktop elementary-standard elementary-minimal
COMPONENTS='main restricted universe multiverse'

add_chroot_hook update-apt-file-cache
add_chroot_hook update-apt-xapian-index
add_chroot_hook update-mlocate-database
add_chroot_hook remove-dbus-machine-id
add_chroot_hook remove-openssh-server-host-keys
add_chroot_hook remove-udev-persistent-rules

lb config noauto \
    --architecture "$ARCH" \
	--mode ubuntu \
	--distribution "$SUITE" \
	--bootstrap-keyring ubuntu-keyring \
    --syslinux-theme elementary-@SYSLINUX \
	--binary-images "$BINARY_IMAGES" \
	--memtest "$MEMTEST" \
	$SOURCE \
	--build-with-chroot false \
	${MIRROR:+--parent-mirror-bootstrap $MIRROR} \
	${COMPONENTS:+--parent-archive-areas "$COMPONENTS"} \
	${KERNEL_FLAVOURS:+--linux-flavours "$KERNEL_FLAVOURS"} \
	--initsystem none \
	--bootloader "$BOOTLOADER" \
	--initramfs-compression gzip \
	$OPTS

echo "LB_CHROOT_HOOKS=\"$CHROOT_HOOKS\"" >> config/chroot
echo "LB_BINARY_HOOKS=\"$BINARY_HOOKS\"" >> config/binary

cp auto/hooks/* config/hooks/

mkdir -p config/archives
cp auto/archives/* config/archives/

# set ISO properties
sed -i 's/Ubuntu\ Live/elementary\ OS/' config/binary
sed -i 's/LB_ISO_VOLUME/LB_ISO_VOLUME\=\"elementary OS\"\n#/' config/binary

# replace channel and suite
sed -i "s/@CHANNEL/$CHANNEL/" config/archives/*.list
sed -i "s/@SUITE/$SUITE/" config/archives/*.list